name: Publish to NPM

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: node test/validateModuleExportsMatchCommonJS/index.js
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
